name: morning-run
on:
  schedule:
    - cron: "10 6 * * *"   # 08:10 Europe/Copenhagen (UTC i Actions)
  workflow_dispatch: {}
jobs:
  morning:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Copenhagen
      ODDSAPI_KEY: ${{ secrets.ODDSAPI_KEY }}
      APIFOOTBALL_KEY: ${{ secrets.APIFOOTBALL_KEY }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
    concurrency:
      group: morning
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: DB sanity
        run: |
          python - <<'PY'
          import os
          from sqlalchemy import create_engine
          url=os.environ["POSTGRES_URL"]
          print("URL prefix:", url.split("@")[0])
          e=create_engine(url, pool_pre_ping=True)
          with e.connect() as c:
              print("now():", c.exec_driver_sql("select now()\n").scalar())
          PY

      - name: Fetch API-Football odds (next 2 days incl. OU/AH)
        env:
          APIFOOTBALL_KEY: ${{ secrets.APIFOOTBALL_KEY }}
        run: |
          set -e
          python scripts/fetch_apifootball_odds.py \
            --days 2 \
            --include-ou25 --include-ah --write-parquet

      - name: Build features — show CLI
        run: |
          python scripts/build_features.py --help || true

      - name: Build features (harvest → merge+write)
        env:
          APIFOOTBALL_KEY: ${{ secrets.APIFOOTBALL_KEY }}
        run: |
          set -e
          python scripts/build_features.py --harvest-postmatch
          python scripts/build_features.py --merge-train-stats-from-db --write-train-set

      - name: Sanity: check train_set.parquet
        run: |
          python - <<'PY'
          import os
          p = "data/features/train_set.parquet"
          print("✅ Found:", os.path.exists(p), "| Path:", p)
          PY

      - name: Train models (1x2 / ou25 / ahm05)
        env:
          APIFOOTBALL_KEY: ${{ secrets.APIFOOTBALL_KEY }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: python scripts/train_models.py

      - name: Predict upcoming + log picks (1x2, OU2.5, AH-0.5)
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: |
          python scripts/predict_upcoming.py \
            --days 2 \
            --offline-only \
            --no-oddsapi \
            --markets 1x2,ou25,ahm05 \
            --min-ev 0.00 --top-k 100 \
            --log-bets \
            --postgres-url "$POSTGRES_URL"
