name: morning-run
on:
  schedule:
    - cron: "10 6 * * *"   # 08:10 Europe/Copenhagen (UTC i Actions)
  workflow_dispatch: {}
jobs:
  morning:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Copenhagen
      ODDSAPI_KEY: ${{ secrets.ODDSAPI_KEY }}
      APIFOOTBALL_KEY: ${{ secrets.APIFOOTBALL_KEY }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
    concurrency:
      group: morning
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install "psycopg[binary]" "sqlalchemy>=2.0"
      - name: Build features
        run: |
          python scripts/build_features.py \
            --season 2025 --leagues 39,140,78 \
            --with-stats --with-stats-limit 40 --with-stats-sleep 0.25
      - name: Train models
        run: python scripts/train_models.py
      - name: Picks + log to Postgres
        run: |
          python scripts/predict_upcoming.py \
            --days 21 --require-real-odds \
            --min-ev 0.02 --min-kelly 0.01 --top-k 25 \
            --export-md --log-bets \
            --postgres-url "$POSTGRES_URL"
