name: morning-run
on:
  schedule:
    - cron: "10 6 * * *"
  workflow_dispatch: {}
jobs:
  morning:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Copenhagen
      ODDSAPI_KEY: ${{ secrets.ODDSAPI_KEY }}
      APIFOOTBALL_KEY: ${{ secrets.APIFOOTBALL_KEY }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
    concurrency:
      group: morning
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Prepare workspace dirs
        run: |
          mkdir -p data/features data/odds_history data/picks data/ledger
          ls -alh data || true

      - name: DB sanity (echo only)
        run: |
          echo "Using POSTGRES_URL prefix: ${POSTGRES_URL%%@*}"

      - name: Fetch API-Football odds (next 2 days incl OU/AH)
        env:
          APIFOOTBALL_KEY: ${{ secrets.APIFOOTBALL_KEY }}
        run: |
          set -e
          python scripts/fetch_apifootball_odds.py \
            --days 2 \
            --include-ou25 --include-ah --write-parquet

      - name: Build features show CLI
        run: |
          python scripts/build_features.py --help || true

      - name: Build features harvest and merge
        env:
          APIFOOTBALL_KEY: ${{ secrets.APIFOOTBALL_KEY }}
        run: |
          set -e
          python scripts/build_features.py --harvest-postmatch --days-back 30 --days-fwd 0
          python scripts/build_features.py --merge-train-stats-from-db --write-train-set

      - name: Sanity check train_set.parquet
        run: |
          if [ -f "data/features/train_set.parquet" ]; then
            echo "Found: data/features/train_set.parquet"
          else
            echo "Missing: data/features/train_set.parquet" >&2
            exit 1
          fi

      - name: Diagnose missing train_set
        if: ${{ failure() }}
        run: |
          echo "Listing data/features:" && ls -alh data/features || true

      - name: Train models (1x2 / ou25 / ahm05)
        env:
          APIFOOTBALL_KEY: ${{ secrets.APIFOOTBALL_KEY }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: python scripts/train_models.py

      - name: Predict upcoming and log picks
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: |
          python scripts/predict_upcoming.py \
            --days 2 \
            --offline-only \
            --no-oddsapi \
            --markets 1x2,ou25,ahm05 \
            --min-ev 0.00 --top-k 100 \
            --log-bets \
            --postgres-url "$POSTGRES_URL"
