name: snapshots

on:
  schedule:
    # Hver 10. minut fra 06:00–23:00 DK (≈ 04–21 UTC afh. af DST)
    - cron: "*/10 4-21 * * *"
  workflow_dispatch:

jobs:
  snapshots:
    runs-on: ubuntu-latest
    concurrency:
      group: snapshots
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Env
        run: |
          echo "POSTGRES_URL=${{ secrets.POSTGRES_URL }}" >> $GITHUB_ENV
          echo "APIFOOTBALL_KEY=${{ secrets.APIFOOTBALL_KEY }}" >> $GITHUB_ENV
          echo "ODDSAPI_KEY=${{ secrets.ODDSAPI_KEY }}" >> $GITHUB_ENV

      - name: DB sanity
        run: |
          python - <<'PY'
          import os
          from sqlalchemy import create_engine
          url=os.environ["POSTGRES_URL"]
          print("URL prefix:", url.split("@")[0])
          e=create_engine(url, pool_pre_ping=True)
          with e.connect() as c:
              print("now():", c.exec_driver_sql("select now()").scalar())
          PY

      - name: Fetch API-Football odds (imminent 180m)
        continue-on-error: true
        run: |
          python scripts/fetch_apifootball_odds.py \
            --imminent-mins 180 \
            --include-ou25 --include-ah --write-parquet || true

      - name: Build features (merge-from-DB + auto-repair)
        run: |
          python scripts/build_features.py --merge-train-stats-from-db

      - name: Health check (train_set if present)
        run: |
          python - <<'PY'
          import os, sys, pandas as pd
          p = "data/features/train_set.parquet"
          if not os.path.exists(p):
              print("ℹ️ train_set.parquet not found yet — likely first run with no harvested data. Skipping hard fail.")
              sys.exit(0)
          try:
              df = pd.read_parquet(p)
              print("train rows:", len(df))
              # allow empty on first few runs, just print a warning
              if len(df) == 0:
                  print("⚠️ train_set exists but is empty — will be populated after harvest/train.")
              sys.exit(0)
          except Exception as e:
              print("health failed:", e)
              sys.exit(1)
          PY
