name: snapshots

on:
  schedule:
 - cron: "*/10 4-21 * * *"
  workflow_dispatch: {}

jobs:
  snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Env
        run: |
          echo "POSTGRES_URL=${{ secrets.POSTGRES_URL }}" >> $GITHUB_ENV
          echo "APIFOOTBALL_KEY=${{ secrets.APIFOOTBALL_KEY }}" >> $GITHUB_ENV
          echo "ODDSAPI_KEY=${{ secrets.ODDSAPI_KEY }}" >> $GITHUB_ENV

      - name: Fetch API-Football odds (imminent 180m)
        continue-on-error: true
        run: |
          python scripts/fetch_apifootball_odds.py --imminent-mins 180 || true

      - name: Build features (merge-from-DB + auto-repair)
        run: |
          python scripts/build_features.py --merge-train-stats-from-db

      - name: Health check
        run: |
          python - <<'PY'
          import pandas as pd, sys
          try:
              df = pd.read_parquet("data/features/train_set.parquet")
              print("train rows:", len(df))
              assert len(df) > 0
          except Exception as e:
              print("health failed:", e)
              sys.exit(1)
          PY
