name: nightly-train

on:
  schedule:
    # 03:15 Europe/Copenhagen ≈ 01:15 UTC (DST). Justeres automatisk i DK.
    - cron: "15 1 * * *"
  workflow_dispatch: {}

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Env
        run: |
          echo "POSTGRES_URL=${{ secrets.POSTGRES_URL }}" >> $GITHUB_ENV
          echo "APIFOOTBALL_KEY=${{ secrets.APIFOOTBALL_KEY }}" >> $GITHUB_ENV
          echo "ODDSAPI_KEY=${{ secrets.ODDSAPI_KEY }}" >> $GITHUB_ENV

      - name: Build features — merge stats from DB (+auto-repair)
        run: |
          python scripts/build_features.py --merge-train-stats-from-db

      - name: Train models
        run: |
          python scripts/train_models.py

      - name: Artifacts (models)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: models-nightly
          path: |
            models/*.pkl
            models/*.json

  settle:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Env
        run: |
          echo "POSTGRES_URL=${{ secrets.POSTGRES_URL }}" >> $GITHUB_ENV
      - name: Settle local ledger (best-effort)
        run: |
          python scripts/predict_upcoming.py --settle --settle-lookback-days 35 || true
